### PR TITLE
WIP: topolvm lvmd deployed as daemonset

### PR DESCRIPTION
**Pull request by jmolmo**
Remove lvmd container from node deployment. Deploy lvmd as Daemonset.

@little-guy-lxr : I do not know if i have choose the better place to call "MakeLvmdDaemonSet". Any suggestions will be welcome.

This is on-going. Because we need to add this PR some CI tests,  and collect more  ideas.

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

### CODE REVIEW

**Comment by little-guy-lxr** [comment]
@jmolmo  if deploy lvmd ad `Daemonset`, how could you fix different node may has diifferent lvmd config. we use `Deployment` to deploy lvmd because we want to make user's could config each node lvmd.  A lvmd `ConfigMap` map A lvmd `Deployment`.

**Comment by little-guy-lxr** [comment]
@jmolmo  you should make this pr to branch(origin-topolvm).

**Comment by jmolmo** [comment]
> @jmolmo you should make this pr to branch(origin-topolvm).
@little-guy-lxr :  Why? i think we must work in this branch. And convert this branch (asap) to  be the "main" branch. See my comments:  https://github.com/alauda/topolvm-operator/issues/23#issuecomment-968869998

**Comment by jmolmo** [comment]
> @jmolmo thanks your contribution . if deploy lvmd as `Daemonset`, how could you fix different node may has diifferent lvmd config. we use `Deployment` to deploy lvmd because we want to let user could config each node lvmd. A lvmd `ConfigMap` map a lvmd `Deployment`.

@little-guy-lxr : Thanks for your comments. 

First of all, this pull request is motivated because your [suggestions(point 2)](https://github.com/alauda/topolvm-operator/issues/23#issuecomment-949332707) about the things we will need to return to use "original topolvm" image.

I do not understand well your comment, (maybe i miss something). We have the cluster.crd to specify the different device and device classes configurations for the different nodes, the configmaps generated by "prepareVolumeGroupJob" use this information to generate a lvmdconfig-<node> configmap for each node. This is done by the "PrepareVolumeGroupVG" , so if after the creation of the cms, we deploy the lvmd daemonset we will  have different lvmd config for each node.  Is correct?

**Comment by little-guy-lxr** [comment]
> > @jmolmo thanks your contribution . if deploy lvmd as `Daemonset`, how could you fix different node may has diifferent lvmd config. we use `Deployment` to deploy lvmd because we want to let user could config each node lvmd. A lvmd `ConfigMap` map a lvmd `Deployment`.
> 
> @little-guy-lxr : Thanks for your comments.
> 
> First of all, this pull request is motivated because your [suggestions(point 2)](https://github.com/alauda/topolvm-operator/issues/23#issuecomment-949332707) about the things we will need to return to use "original topolvm" image.
> 
> I do not understand well your comment, (maybe i miss something). We have the cluster.crd to specify the different device and device classes configurations for the different nodes, the configmaps generated by "prepareVolumeGroupJob" use this information to generate a lvmdconfig- configmap for each node. This is done by the "PrepareVolumeGroupVG" , so if after the creation of the cms, we deploy the lvmd daemonset we will have different lvmd config for each node. Is correct?

@jmolmo  `PrepareVolumeGroupVGJob` will create lvmd configmap for each node， the lvmd configmap of each node is different. but if you use daemonet, there is no way to specify which lvmd pod uses which lvmd configmap.

**Comment by leelavg** [comment]
1. sorry for the interlude, currently operator uses lvmd from original topolvm project but deploys as part of a node deployment
2. original project suggests to deploy lvmd as a daemon-set but it all depends upon the availability of lvmd sock
3. having said that, it's best to deploy both nodeplugin and lvmd as a daemonset majorly due to upgrade scenarios where all deployments except ds can be drained and node can be upgraded
4. I didn't had a look into original topolvm project about the persistence needed for lvmd sock file, I feel that should be present when we do any lvm ops so we can get aways by deploying that using deployment

@little-guy-lxr what effort is pending as per you to make `origin-topolvm` as the main branch and contribute to that single branch?

pls comment your thoughts on this.

**Comment by little-guy-lxr** [comment]
> 1. sorry for the interlude, currently operator uses lvmd from original topolvm project but deploys as part of a node deployment
> 2. original project suggests to deploy lvmd as a daemon-set but it all depends upon the availability of lvmd sock
> 3. having said that, it's best to deploy both nodeplugin and lvmd as a daemonset majorly due to upgrade scenarios where all deployments except ds can be drained and node can be upgraded
> 4. I didn't had a look into original topolvm project about the persistence needed for lvmd sock file, I feel that should be present when we do any lvm ops so we can get aways by deploying that using deployment
> 
> @little-guy-lxr what effort is pending as per you to make `origin-topolvm` as the main branch and contribute to that single branch?
> 
> pls comment your thoughts on this.

1. mutation  webhook cert now is  manually generated, we should use cert-manager or init container to generate. see https://github.com/alauda/topolvm-operator/issues/62
2.

**Comment by jmolmo** [comment]
> @jmolmo `PrepareVolumeGroupVGJob` will create lvmd configmap for each node， the lvmd configmap of each node is different. but if you use daemonet, there is no way to specify which lvmd pod uses which lvmd configmap.

@little-guy-lxr : Each configmap has a name that allow to identify the node.  So it seems easy to link each pod with the right configmap. Can you explain why you say that this is not possible?

```
# kubectl get configmap -n topolvm-system
NAME                            DATA   AGE
kube-root-ca.crt                1      15h
lvmdconfig-k8s-master-00.rook   3      15h
lvmdconfig-k8s-worker-00.rook   3      15h
lvmdconfig-k8s-worker-01.rook   3      15h
tooplvm-operator-setting        2      15h
topolvm                         0      15h

# kubectl get nodes
NAME                 STATUS   ROLES                  AGE   VERSION
k8s-master-00.rook   Ready    control-plane,master   15h   v1.22.3
k8s-worker-00.rook   Ready    <none>                 15h   v1.22.3
k8s-worker-01.rook   Ready    <none>                 15h   v1.22.3

```

**Comment by little-guy-lxr** [comment]
> > @jmolmo `PrepareVolumeGroupVGJob` will create lvmd configmap for each node， the lvmd configmap of each node is different. but if you use daemonet, there is no way to specify which lvmd pod uses which lvmd configmap.
> 
> @little-guy-lxr : Each configmap has a name that allow to identify the node. So it seems easy to link each pod with the right configmap. Can you explain why you say that this is not possible?
> 
> ```
> # kubectl get configmap -n topolvm-system
> NAME                            DATA   AGE
> kube-root-ca.crt                1      15h
> lvmdconfig-k8s-master-00.rook   3      15h
> lvmdconfig-k8s-worker-00.rook   3      15h
> lvmdconfig-k8s-worker-01.rook   3      15h
> tooplvm-operator-setting        2      15h
> topolvm                         0      15h
> 
> # kubectl get nodes
> NAME                 STATUS   ROLES                  AGE   VERSION
> k8s-master-00.rook   Ready    control-plane,master   15h   v1.22.3
> k8s-worker-00.rook   Ready    <none>                 15h   v1.22.3
> k8s-worker-01.rook   Ready    <none>                 15h   v1.22.3
> ```

@jmolmo  sorry, I am not sure how to mount multiple configmaps on one daemonset. and link pod that generated by daemonset with the right configmap . Can you give an example？ thanks

**Comment by leelavg** [comment]
> 2. the workload selection of lvmd . I think if we want to modify from deployment to daemonset. we should make a plan that could distinguish each node's lvmd configmap. as you know, daemonset dosn't distinguish it.

@little-guy-lxr do you see this as a hard requirement? Even with the current `origin-topolvm` branch I could do basic testing without any issues but still early to write it off.

So, is it possible to expand this point a bit more about any known issues if we continue deploying lvmd as part of nodeplugin but not as daemonset?

**Comment by little-guy-lxr** [comment]
@jmolmo  could  you make this pr to branch origin-topolvm. we will delete branch origin-topolvm-image prevent push pr to incorrect branch.

**Comment by jmolmo** [comment]
@little-guy-lxr : lets discuss the implementation to follow in:
https://github.com/alauda/topolvm-operator/issues/71

Closing this for the moment

**Pull request closed without merging**
