### PR TITLE
Deploy single controller for a single node cluster

### PR DESCRIPTION
**Pull request by leelavg**
- Minor changes to e2e/Makefile to deploy operator
using pre generated example yaml

### CODE REVIEW

**Comment by leelavg** [comment]
@little-guy-lxr 
- I think I made some mistake in https://github.com/alauda/topolvm-operator/pull/92#issuecomment-981296326 not totally related to this PR though
- After that change, I could only see `status.phase` and `status.nodestoragestate.{node,phase}` are being updated, will look into it at the earliest
- If nothing's working I'll use the old v2 CRD as it is

**Comment by leelavg** [comment]
@little-guy-lxr 

- little help if you don't mind, where exactly the cluster cr status is being updated
- not the node status and phase but from where the success and failclasses is being updated in cluster CR

**Comment by little-guy-lxr** [comment]
> @little-guy-lxr
> 
> * little help if you don't mind, where exactly the cluster cr status is being updated
> * not the node status and phase but from where the success and failclasses is being updated in cluster CR

@leelavg  Thank you very much for your advice.

1. now the cluster phase  is only check whether topolvm-node  pod is running. Because although maybe all vg were created succesfully, if node down, we should notify this event to user in time. And I think the CR status should be re-arch. The state should be displayed on a node basis.

such as:
```yaml
  status:
    nodeStorageState:
    - node: 192.168.16.212
      phase: Ready
      deviceClassState:
      -  className: osd-meta
         state:  Ready
         vgName: osd-meta
         deviceStates:
          - name: /dev/sdb
             state: Online
    phase: Ready
```

2. [use operator-sdk for sdk](https://github.com/alauda/topolvm-operator/pull/92#issuecomment-981296326) `make deploy ` seems miss CSIDriver resource.

**Comment by leelavg** [comment]
- ack, found the issue. It's due to `omitempty` vs `//+optional`
- consider below examples
type1:
```
//+optional
FailClasses []ClassState `json:"failClasses"`
```
type2:
```
FailClasses []ClassState `json:"failClasses,omitempty"`
```
- `make generate manifest` would generate same CRD for both types above
- however we are actually updating only `status.phase` and `state.nodeStorageState.{node,phase}` in `updateStatus`
- so if we have type1 then CR status would just have earlier values (which lvmd controller updates) and only above three fields are updated in every reconcile
- but in type2 field itself has `omitempty` and so only above three fields are updated and all other previous fields statuses are discared


- so yes, as a first step it's better to reconcile CR status of every field to be sure everytime and re-arch of CRD may not be needed immediately i guess.

**Comment by leelavg** [comment]
@little-guy-lxr 

- I'm not going to send any commits to this PR
- Pls review and merge if it looks good to you

**Comment by little-guy-lxr** [comment]
> 2\. [use operator-sdk for sdk](https://github.com/alauda/topolvm-operator/pull/92#issuecomment-981296326) `make deploy ` seems miss CSIDriver resource.

 @leelavg  `make deploy` and `make example`  seems miss CSIDriver resource. can you add it in this PR ?


```
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: topolvm.cybozu.com
spec:
  attachRequired: false
  podInfoOnMount: true
  storageCapacity: true
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
```

**Pull request merged**
