### PR TITLE
fix #65

### LINKED ISSUE #65: Failed to create (intermittent) prepareVG job on AWS
- Did the usual, created a OCP cluster, added disks, installed operator etc
- Operator Image (created from `origin-topolvm` branch): `quay.io/rhn_support_lgangava/toperator:origin`

- Issue:
1. Unable to deploy pod for preparing volume group
```
# k describe jobs topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal                                                                                                             
Name:             topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal                                                                                                             
Namespace:        topolvm-system  
[...]
Events:
  Type     Reason        Age   From            Message
  ----     ------        ----  ----            -------
Warning  FailedCreate  30s   job-controller  Error creating: Pod "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-wxw6f" is invalid: [metadata.generateName: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), metadata.name: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.--1-wxw6f": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')]
[...]
```
- Corresponding code lgtm but not sure why the pod name is starting with double hyphens `--1-` 🤔 
https://github.com/alauda/topolvm-operator/blob/dad1c0a07d8bbe436c79301208d15b0e1806754f/pkg/operator/volumegroup/vgmanager.go#L144-L151

### PR DESCRIPTION
**Pull request by little-guy-lxr**
1. upgrade client-go version
2, add k8s version for e2e

### CODE REVIEW

**Comment by leelavg** [comment]
- Wondering how you are able to build the binary without updating the Dockerfile https://github.com/alauda/topolvm-operator/blob/2e3b0eda6f03badb42d6201cd9e05312576e81bf/Dockerfile#L3
- I added client-go `v0.22.3` in `go.mod` and build failed with `package io/fs is not in GOROOT` 
- so better update it in Dockerfile as well?

**Comment by leelavg** [comment]
- btw, below was the patch that I thought of to support versions before 1.22 as well
``` diff
diff --git a/pkg/operator/volumegroup/vgmanager.go b/pkg/operator/volumegroup/vgmanager.go
index b2f3d37..f5ec20b 100644
--- a/pkg/operator/volumegroup/vgmanager.go
+++ b/pkg/operator/volumegroup/vgmanager.go
@@ -18,6 +18,7 @@ package volumegroup
 
 import (
 	"fmt"
+
 	"github.com/alauda/topolvm-operator/pkg/cluster"
 	"github.com/alauda/topolvm-operator/pkg/operator/k8sutil"
 	"github.com/coreos/pkg/capnslog"
@@ -32,13 +33,38 @@ var (
 	logger = capnslog.NewPackageLogger("topolvm/operator", "volume-group")
 )
 
-func makeJob(nodeName string, image string, reference *metav1.OwnerReference) (*batch.Job, error) {
+const (
+	indexJobMajorNumber = "1"
+	// from k8s v1.21 job spec can have a field name 'completionMode' which is
+	// in alpha and in v1.22 it's in beta
+	indexJobMinorNumber = "21"
+)
+
+func makeJob(clientset kubernetes.Interface, nodeName string, image string, reference *metav1.OwnerReference) (*batch.Job, error) {
 
 	podSpec, err := provisionPodTemplateSpec(nodeName, image, v1.RestartPolicyNever)
 	if err != nil {
 		return nil, err
 	}
 
+	version, err := clientset.Discovery().ServerVersion()
+	if err != nil {
+		return nil, err
+	}
+
+	jobSpec := batch.JobSpec{
+		Template: *podSpec,
+	}
+
+	if version.Major >= indexJobMajorNumber && version.Minor > indexJobMinorNumber {
+		// workaround for https://github.com/kubernetes/kubernetes/pull/105676
+		// can be removed after merge of above PR, in v1.21 feature gate has to
+		// be enabled so keeping minor number as 22 see below for more info
+		// https://kubernetes.io/blog/2021/04/19/introducing-indexed-jobs/
+		indexed := batch.CompletionMode(batch.IndexedCompletion)
+		jobSpec.CompletionMode = &indexed
+	}
+
 	job := &batch.Job{
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      k8sutil.TruncateNodeName(cluster.PrepareVgJobFmt, nodeName),
@@ -49,9 +75,7 @@ func makeJob(nodeName string, image string, reference *metav1.OwnerReference) (*
 			},
 			OwnerReferences: []metav1.OwnerReference{*reference},
 		},
-		Spec: batch.JobSpec{
-			Template: *podSpec,
-		},
+		Spec: jobSpec,
 	}
 	return job, nil
 
@@ -61,7 +85,7 @@ func MakeAndRunJob(clientset kubernetes.Interface, nodeName string, image string
 	// update the orchestration status of this node to the starting state
 
 	logger.Debugf("start make prepare vg job")
-	job, err := makeJob(nodeName, image, reference)
+	job, err := makeJob(clientset, nodeName, image, reference)
 	if err != nil {
 		logger.Errorf("make job for node:%s failed", nodeName)
 		return err
```

**Comment by little-guy-lxr** [comment]
> * Wondering how you are able to build the binary without updating the Dockerfile for 1.16 https://github.com/alauda/topolvm-operator/blob/2e3b0eda6f03badb42d6201cd9e05312576e81bf/Dockerfile#L3
> * I added client-go `v0.22.3` in `go.mod` and build failed with `package io/fs is not in GOROOT`
> * so better update it in Dockerfile as well?

@leelavg I has updated that in dockerfile.  could you help me debug why go mod incrrect. I guess maybe i use goproxy to speed up pulling github code packages that is out of sync.

**Comment by leelavg** [comment]
@little-guy-lxr works for me
```
-> go env GOPROXY
https://proxy.golang.org,direct

-> gl -n 1
* 977f64b - (34 minutes ago)  (HEAD -> pr70) fix #65 1. upgrade client-go version 2. add k8s version for e2e <little-guy-lxr>
```

```
go fmt ./...
go vet ./...
/root/toolbox/orc/topolvm-operator/bin/staticcheck ./...
/root/toolbox/orc/topolvm-operator/bin/ineffassign ./...
sudo go test -race -v $(go list ./... | grep -v vendor | grep -v e2e)
?   	github.com/alauda/topolvm-operator	[no test files]
?   	github.com/alauda/topolvm-operator/api/v1	[no test files]
=== RUN   TestNewSecurityContextConstraints
--- PASS: TestNewSecurityContextConstraints (0.00s)
PASS
ok  	github.com/alauda/topolvm-operator/api/v2	(cached)
?   	github.com/alauda/topolvm-operator/cmd/conversion	[no test files]
?   	github.com/alauda/topolvm-operator/cmd/discover	[no test files]
?   	github.com/alauda/topolvm-operator/cmd/operator	[no test files]
?   	github.com/alauda/topolvm-operator/cmd/preparevg	[no test files]
?   	github.com/alauda/topolvm-operator/cmd/topolvm	[no test files]
?   	github.com/alauda/topolvm-operator/controllers	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/apis	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/cluster	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/converter	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/gencert	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/metric	[no test files]
=== RUN   TestAddFinalizerIfNotPresent
2021-11-16 15:10:34.903149 I | topolvm-spec: adding finalizer ".topolvm.cybozu.com" on "test"
--- PASS: TestAddFinalizerIfNotPresent (0.00s)
=== RUN   TestRemoveFinalizer
2021-11-16 15:10:34.904726 I | topolvm-spec: removing finalizer "topolvmcluster.topolvm.cybozu.com" on "test"
--- PASS: TestRemoveFinalizer (0.00s)
=== RUN   TestMatch
--- PASS: TestMatch (0.00s)
PASS
ok  	github.com/alauda/topolvm-operator/pkg/operator/controller	(cached)
?   	github.com/alauda/topolvm-operator/pkg/operator/csidriver	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/operator/discover	[no test files]
=== RUN   TestDeleteConfigMap
--- PASS: TestDeleteConfigMap (0.00s)
=== RUN   TestCreateReplaceableConfigmap
2021-11-16 15:10:47.310164 I | op-k8sutil: Removing previous cm test-configmap to start a new one
--- PASS: TestCreateReplaceableConfigmap (0.00s)
=== RUN   TestDeleteResource
verifyCount: 1    - returnNilAt: 1000000
2021-11-16 15:10:47.311455 I | op-k8sutil: Retrying 2 more times every 0 seconds for test resource name to be deleted
verifyCount: 2    - returnNilAt: 1000000
2021-11-16 15:10:47.313767 I | op-k8sutil: Retrying 1 more times every 0 seconds for test resource name to be deleted
verifyCount: 3    - returnNilAt: 1000000
2021-11-16 15:10:47.315379 I | op-k8sutil: Retrying 0 more times every 0 seconds for test resource name to be deleted
verifyCount: 4    - returnNilAt: 1000000
2021-11-16 15:10:47.315678 I | op-k8sutil: Retrying 2 more times every 0 seconds for test resource name to be deleted
verifyCount: 5    - returnNilAt: 1000000
2021-11-16 15:10:47.317330 I | op-k8sutil: Retrying 1 more times every 0 seconds for test resource name to be deleted
verifyCount: 6    - returnNilAt: 1000000
2021-11-16 15:10:47.318704 I | op-k8sutil: Retrying 0 more times every 0 seconds for test resource name to be deleted
2021-11-16 15:10:47.318834 W | op-k8sutil: failed to delete test resource name. gave up waiting after 2 retries every 0s seconds. still not verified
verifyCount: 1    - returnNilAt: 2
2021-11-16 15:10:47.318946 I | op-k8sutil: Retrying 2 more times every 0 seconds for test resource name to be deleted
verifyCount: 2    - returnNilAt: 2
verifyCount: 1    - returnNilAt: 1000000
2021-11-16 15:10:47.320479 I | op-k8sutil: Retrying 5 more times every 0 seconds for test resource name to be deleted
verifyCount: 2    - returnNilAt: 1000000
2021-11-16 15:10:47.322865 I | op-k8sutil: Retrying 4 more times every 0 seconds for test resource name to be deleted
verifyCount: 3    - returnNilAt: 1000000
2021-11-16 15:10:47.325799 I | op-k8sutil: Retrying 3 more times every 0 seconds for test resource name to be deleted
verifyCount: 4    - returnNilAt: 1000000
2021-11-16 15:10:47.328706 I | op-k8sutil: Retrying 2 more times every 0 seconds for test resource name to be deleted
verifyCount: 5    - returnNilAt: 1000000
2021-11-16 15:10:47.331141 I | op-k8sutil: Retrying 1 more times every 0 seconds for test resource name to be deleted
verifyCount: 6    - returnNilAt: 1000000
2021-11-16 15:10:47.334014 I | op-k8sutil: Retrying 0 more times every 0 seconds for test resource name to be deleted
--- PASS: TestDeleteResource (0.02s)
=== RUN   TestCreateDeployment
--- PASS: TestCreateDeployment (0.00s)
=== RUN   TestDeleteDeployment
2021-11-16 15:10:47.336832 I | op-k8sutil: removing deployment test-deployment if it exists
2021-11-16 15:10:47.337055 I | op-k8sutil: Removed deployment test-deployment
2021-11-16 15:10:47.337305 I | op-k8sutil: confirmed test-deployment does not exist
--- PASS: TestDeleteDeployment (0.00s)
=== RUN   TestTruncateNodeName
2021-11-16 15:10:47.338304 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName k8s-worker-1234567890.this.is.a.very.very.long.node.name.example.com will be 801a3ba95fe6ce6a3bd879552ca2a8b0
2021-11-16 15:10:47.338627 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName k8s-worker-1234567890.this.is.a.very.very.long.node.name.example.com will be 801a3ba95fe6ce6a3bd879552ca2a8b0
2021-11-16 15:10:47.338861 I | op-k8sutil: format and nodeName longer than 63 chars, nodeName k8s-worker-1234567890.this.is.a.very.very.long.node.name.example.com will be 801a3ba95fe6ce6a3bd879552ca2a8b0
--- PASS: TestTruncateNodeName (0.00s)
=== RUN   TestGetContainerInPod
--- PASS: TestGetContainerInPod (0.00s)
PASS
ok  	github.com/alauda/topolvm-operator/pkg/operator/k8sutil	(cached)
?   	github.com/alauda/topolvm-operator/pkg/operator/monitor	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/operator/node	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/operator/psp	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/operator/volumectr	[no test files]
?   	github.com/alauda/topolvm-operator/pkg/operator/volumegroup	[no test files]
=== RUN   Test_assertErrorType
=== RUN   Test_assertErrorType/unknown_error_type
=== RUN   Test_assertErrorType/exec.exitError_type
=== RUN   Test_assertErrorType/exec.Error_type
--- PASS: Test_assertErrorType (0.01s)
    --- PASS: Test_assertErrorType/unknown_error_type (0.00s)
    --- PASS: Test_assertErrorType/exec.exitError_type (0.00s)
    --- PASS: Test_assertErrorType/exec.Error_type (0.00s)
PASS
ok  	github.com/alauda/topolvm-operator/pkg/util/exec	(cached)
?   	github.com/alauda/topolvm-operator/pkg/util/exec/test	[no test files]
=== RUN   TestStringFlags
--- PASS: TestStringFlags (0.00s)
=== RUN   TestGetFlagsAndValues
--- PASS: TestGetFlagsAndValues (0.00s)
PASS
ok  	github.com/alauda/topolvm-operator/pkg/util/flags	(cached)
=== RUN   TestFindUUID
--- PASS: TestFindUUID (0.00s)
=== RUN   TestParseFileSystem
--- PASS: TestParseFileSystem (0.00s)
=== RUN   TestGetPartitions
2021-11-16 15:10:46.395943 I | sys: run 1 command lsblk
2021-11-16 15:10:46.396378 I | sys: Output: NAME="sdc" SIZE="100000" TYPE="disk" PKNAME=""
2021-11-16 15:10:46.396480 I | sys: Device found - sdc
2021-11-16 15:10:46.396648 I | sys: run 2 command lsblk
2021-11-16 15:10:46.396757 I | sys: Output: NAME="sdb" SIZE="65" TYPE="disk" PKNAME=""
NAME="sdb2" SIZE="10" TYPE="part" PKNAME="sdb"
NAME="sdb3" SIZE="20" TYPE="part" PKNAME="sdb"
NAME="sdb1" SIZE="30" TYPE="part" PKNAME="sdb"
2021-11-16 15:10:46.396841 I | sys: Device found - sdb
2021-11-16 15:10:46.396940 I | sys: run 3 command udevadm
2021-11-16 15:10:46.397139 I | sys: run 4 command udevadm
2021-11-16 15:10:46.397394 I | sys: run 5 command udevadm
2021-11-16 15:10:46.397646 I | sys: run 6 command lsblk
2021-11-16 15:10:46.397758 I | sys: Output: NAME="sda" SIZE="19818086400" TYPE="disk" PKNAME=""
NAME="sda4" SIZE="1073741824" TYPE="part" PKNAME="sda"
NAME="sda2" SIZE="2097152" TYPE="part" PKNAME="sda"
NAME="sda9" SIZE="17328766976" TYPE="part" PKNAME="sda"
NAME="sda7" SIZE="67108864" TYPE="part" PKNAME="sda"
NAME="sda3" SIZE="1073741824" TYPE="part" PKNAME="sda"
NAME="usr" SIZE="1065345024" TYPE="crypt" PKNAME="sda3"
NAME="sda1" SIZE="134217728" TYPE="part" PKNAME="sda"
NAME="sda6" SIZE="134217728" TYPE="part" PKNAME="sda"
2021-11-16 15:10:46.397866 I | sys: Device found - sda
2021-11-16 15:10:46.398000 I | sys: run 7 command udevadm
2021-11-16 15:10:46.398094 I | sys: run 8 command udevadm
2021-11-16 15:10:46.398212 I | sys: run 9 command udevadm
2021-11-16 15:10:46.398359 I | sys: run 10 command udevadm
2021-11-16 15:10:46.398494 I | sys: run 11 command udevadm
2021-11-16 15:10:46.398672 I | sys: run 12 command udevadm
2021-11-16 15:10:46.398803 I | sys: run 13 command udevadm
2021-11-16 15:10:46.398930 I | sys: run 14 command lsblk
2021-11-16 15:10:46.404063 I | sys: Output: NAME="dm-0" SIZE="100000" TYPE="lvm" PKNAME=""
NAME="ceph--89fa04fa--b93a--4874--9364--c95be3ec01c6-osd--data--70847bdb--2ec1--4874--98ba--d87d4860a70d" SIZE="31138512896" TYPE="lvm" PKNAME=""
2021-11-16 15:10:46.404468 I | sys: Device found - dm-0
2021-11-16 15:10:46.404795 I | sys: run 15 command lsblk
2021-11-16 15:10:46.404876 I | sys: Output: 
--- PASS: TestGetPartitions (0.01s)
=== RUN   TestParseUdevInfo
--- PASS: TestParseUdevInfo (0.00s)
=== RUN   TestListDevicesChildListDevicesChild
2021-11-16 15:10:46.408481 I | sys: command lsblk
--- PASS: TestListDevicesChildListDevicesChild (0.00s)
=== RUN   TestCreatePhysicalVolume
--- PASS: TestCreatePhysicalVolume (0.60s)
=== RUN   TestCreateVolumeGroup
--- PASS: TestCreateVolumeGroup (0.90s)
=== RUN   TestExpandVolumeGroup
--- PASS: TestExpandVolumeGroup (1.28s)
=== RUN   TestGetPhysicalVolume
--- PASS: TestGetPhysicalVolume (0.86s)
PASS
ok  	github.com/alauda/topolvm-operator/pkg/util/sys	(cached)
```

**Comment by leelavg** [comment]
- This is also working fine `go clean -testcache; GOPROXY=direct make test`

**Comment by leelavg** [comment]
- Pls take a look when you get time
- I cherry-picked this PR on origin-topolvm branch, created an image and tested the fix but it wasn't working
- I did add below extra code and re-checked again but it didn't work
``` diff
diff --git a/pkg/operator/volumegroup/vgmanager.go b/pkg/operator/volumegroup/vgmanager.go
index 3070cf5..8a3b004 100644
--- a/pkg/operator/volumegroup/vgmanager.go
+++ b/pkg/operator/volumegroup/vgmanager.go
@@ -18,6 +18,7 @@ package volumegroup
 
 import (
        "fmt"
+
        "github.com/alauda/topolvm-operator/pkg/cluster"
        "github.com/alauda/topolvm-operator/pkg/operator/k8sutil"
        "github.com/coreos/pkg/capnslog"
@@ -61,7 +62,11 @@ func makeJob(clientset kubernetes.Interface, nodeName string, image string, refe
                // be enabled so keeping minor number as 22 see below for more info
                // https://kubernetes.io/blog/2021/04/19/introducing-indexed-jobs/
                indexed := batch.CompletionMode(batch.IndexedCompletion)
+               completions := int32(1)
+               parallelism := int32(1)
                jobSpec.CompletionMode = &indexed
+               jobSpec.Completions = &completions
+               jobSpec.Parallelism = &parallelism
        }
 
        job := &batch.Job{
```
- In both the scenarios, I'm hitting below error in operator log
```
2021-11-16 11:10:08.482064 E | volume-group: run job failed for node:ip-10-0-155-231.ap-south-1.compute.internal err:Job.batch "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal" is invalid: metadata.name: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal": will not able to create pod with invalid DNS label: topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal-0
```

1. How come CI is passing without any issues? I wasn't able to create job at all let alone the pod from job.

Pls let me know if more info is required.

**Comment by leelavg** [comment]
- Found the issue

```
# original nodename
echo -n 'ip-10-0-155-231.ap-south-1.compute.internal' | wc -m
43

# after truncate and prefix
echo -n 'topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal' | wc -m
62

# this goes to https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/apis/batch/validation/validation.go#L99-L102
# and the final result will be 64 and so the issue. 
echo -n 'topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal-0' | wc -m
64
```
It's better to reduce `cluster.PrepareVgJobFmt` to minimum possible value as jobs will be created in a single namespace and there'll no ambiguity

**Comment by little-guy-lxr** [comment]
> * Pls take a look when you get time
> * I cherry-picked this PR on origin-topolvm branch, created an image and tested the fix but it wasn't working
> * I did add below extra code and re-checked again but it didn't work
> 
> ```diff
> diff --git a/pkg/operator/volumegroup/vgmanager.go b/pkg/operator/volumegroup/vgmanager.go
> index 3070cf5..8a3b004 100644
> --- a/pkg/operator/volumegroup/vgmanager.go
> +++ b/pkg/operator/volumegroup/vgmanager.go
> @@ -18,6 +18,7 @@ package volumegroup
>  
>  import (
>         "fmt"
> +
>         "github.com/alauda/topolvm-operator/pkg/cluster"
>         "github.com/alauda/topolvm-operator/pkg/operator/k8sutil"
>         "github.com/coreos/pkg/capnslog"
> @@ -61,7 +62,11 @@ func makeJob(clientset kubernetes.Interface, nodeName string, image string, refe
>                 // be enabled so keeping minor number as 22 see below for more info
>                 // https://kubernetes.io/blog/2021/04/19/introducing-indexed-jobs/
>                 indexed := batch.CompletionMode(batch.IndexedCompletion)
> +               completions := int32(1)
> +               parallelism := int32(1)
>                 jobSpec.CompletionMode = &indexed
> +               jobSpec.Completions = &completions
> +               jobSpec.Parallelism = &parallelism
>         }
>  
>         job := &batch.Job{
> ```
> 
> * In both the scenarios, I'm hitting below error in operator log
> 
> ```
> 2021-11-16 11:10:08.482064 E | volume-group: run job failed for node:ip-10-0-155-231.ap-south-1.compute.internal err:Job.batch "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal" is invalid: metadata.name: Invalid value: "topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal": will not able to create pod with invalid DNS label: topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal-0
> ```
> 
> 1. How come CI is passing without any issues? I wasn't able to create job at all let alone the pod from job.
> 
> Pls let me know if more info is required.

CI kubernetes version is 1.22.0.  your test k8s version is what?  @leelavg

**Comment by little-guy-lxr** [comment]
> * Found the issue
> 
> ```
> # original nodename
> echo -n 'ip-10-0-155-231.ap-south-1.compute.internal' | wc -m
> 43
> 
> # after truncate and prefix
> echo -n 'topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal' | wc -m
> 62
> 
> # this goes to https://github.com/kubernetes/kubernetes/blob/release-1.22/pkg/apis/batch/validation/validation.go#L99-L102
> # and the final result will be 64 and so the issue. 
> echo -n 'topolvm-prepare-vg-ip-10-0-155-231.ap-south-1.compute.internal-0' | wc -m
> 64
> ```
> 
> It's better to reduce `cluster.PrepareVgJobFmt` to minimum possible value (just `preparevg`?) as jobs will be created in a single namespace and there'll no ambiguity

ok, we could reduce the name of job.

**Comment by leelavg** [comment]
> CI kubernetes version is 1.22.0. your test k8s version is what?

- Mine is also v1.22.0, as later found out it's due the length of node name.
- Since I hit this node length issue twice already, how about we use the node UID for generating job names and nodeplugins as that'll not be more than 40 chars? If that's fine, need to check whether the UID changes after a node reboot or not.

**Comment by little-guy-lxr** [comment]
> > CI kubernetes version is 1.22.0. your test k8s version is what?
> 
> * Mine is also v1.22.0, as later found out it's due the length of node name.
> * Since I hit this node length issue twice already, how about we use the node UID for generating job names and nodeplugins as that'll not be more than 40 chars? If that's fine, need to check whether the UID changes after a node reboot or not.

@leelavg  Check node uid change or not will introduce some complexity. i think we could add a truncateNode func for index job. 
What do you think of this solution？

```go
func truncateNodeNameForIndexJob(format, nodeName string)string{
	if len(nodeName)+len(fmt.Sprintf(format, "")) > validation.DNS1035LabelMaxLength -3 {
		hashed := k8sutil.Hash(nodeName)
		logger.Infof("format and nodeName longer than %d chars, nodeName %s will be %s", validation.DNS1035LabelMaxLength -3, nodeName, hashed)
		nodeName = hashed
	}
	return fmt.Sprintf(format, nodeName)
}

```

**Comment by leelavg** [comment]
- Oh, you pushed the changes, I'm looking into it actually.
- Wanted to be sure that it get through k8s validation as well, seems it isn't https://play.golang.org/p/UWgiXBvM8Dh

**Comment by leelavg** [comment]
- Not sure what's happening with CI, I did `go clean -modcache && go clean -testcache` then also `make test` is working without any issue.

**Comment by little-guy-lxr** [comment]
> * Not sure what's happening with CI, I did `go clean -modcache && go clean -testcache` then also `make test` is working without any issue.

maybe go path incorrect ?   I will continue to check what is the cause

**Comment by leelavg** [comment]
@little-guy-lxr cherry-picked the commits and it worked in my setup as well, need to fix build failure

```
-> k get po,job -l app.kubernetes.io/name=prepare-volume-group
NAME                                                              READY   STATUS      RESTARTS   AGE
pod/topolvm-prepare-vg-b474141ca58b7db8329c746730bc88aa-0-phldt   0/1     Completed   0          4m18s

NAME                                                            COMPLETIONS   DURATION   AGE
job.batch/topolvm-prepare-vg-b474141ca58b7db8329c746730bc88aa   1/1           10s        4m18s


-> gl -n 5
* b5cab79 - (21 minutes ago)  (HEAD -> pr-job) update makefile to remove check-uncommitted <little-guy-lxr>
* f7b91cd - (21 minutes ago)  fix index job name length over 63 <little-guy-lxr>
* d80dc6c - (22 minutes ago)  fix #65 1. upgrade client-go version 2. add k8s version for e2e <little-guy-lxr>
*   29fb862 - (2 days ago)  (original) Merge pull request #68 from alauda/feat/origin-topolvm-image <little-guy-lxr>
|\  
| * e95a058 - (2 days ago)  fix prepare job pod template <little-guy-lxr>
```
- how about removing `k8s.io/client-go v12.0.0+incompatible` from exclude in go.mod?

**Pull request merged**
