### PR TITLE
Operator sdk dev

### PR DESCRIPTION
**Pull request by little-guy-lxr**

### CODE REVIEW

**Comment by little-guy-lxr** [comment]
@leelavg  merge operator-sdk-dev to main branch.

**Comment by leelavg** [comment]
@little-guy-lxr do we really want to merge the branch?

- I feel it'd be better to rename the branch and generate whatever is needed

**Comment by little-guy-lxr** [comment]
> * I feel it'd be better to rename the branch and generate whatever is needed

It is hard to maintain two branches. make operator-sdk-dev as base branch can avoid a lot of conflict.

**Comment by leelavg** [comment]
- ack, I didn't mean to maintain two branches
- we make `operator-sdk-dev` as `main` and current main as something else, the same way we did for `origin-topolvm`
- rationale being, it's easier to reference other branch if something goes wrong in `operator-sdk-dev` rather than going over and reverting commits from same branch
- we will have three branches by the end of it `alauda-topolvm`, `operator-sdk-dev` will become `main`, `main` will become something else like `old-layout`

Will that be fine?

**Pull request closed without merging**
