### PR TITLE
Solve problems starting topolvm-controller using topolvm original image

### PR DESCRIPTION
**Pull request by jmolmo**
This changes must be applied over the changes proposed in:
 https://github.com/alauda/topolvm-operator/pull/36

- Topolvm operator image in topolvm cluster now points to the original topolvm
image.
- Added a self signed certificate to make possible start metric and webhook
https server in topolvm controller
- Added NAMESPACE env var to CSI provisioner container in topolvm controller
- Fix some typos

TODO: Discuss the management of certificates (helm chart vs CRDs)

Signed-off-by: Juan Miguel Olmo Martínez <jolmomar@redhat.com>

### CODE REVIEW

**Comment by jmolmo** [comment]
@little-guy-lxr : 
Probably we need to discuss the use of a predefined certificate in the topolvm-controller htpp servers ( when install using plain crds, not helm chart).  For the moment the important thing for me is just to provide a working copy of the operator, that can be used as base to add new improvements and changes.
After discussion I would be glad to open a new PR to address any kind of change in the certificates part.

**Comment by jmolmo** [comment]
@little-guy-lxr : I will rebase and pass e2e

**Comment by jmolmo** [comment]
I have verified the error in the e2e tests:

```
• Failure [0.068 seconds]
TopoLVM
/home/runner/work/topolvm-operator/topolvm-operator/e2e/suite_test.go:137
  storagecapacity
  /home/runner/work/topolvm-operator/topolvm-operator/e2e/suite_test.go:141
    should csistoragecapacities create and update [It]
    /home/runner/work/topolvm-operator/topolvm-operator/e2e/storagecapacity_test.go:69

    Expected
        <int>: 0
    to equal
        <int>: 3
```

It seems that it is because the command:
`kubectl get csistoragecapacities -o=json -n topolvm-system`
does not return any items...

I do not know what is the cause of this error, because as i understand it depends of the k8 version used, so i do not know why this modification are affecting the e2e test.
In the test cluster i have used for manual testing with this changes, everything works , but the output of the same  command   shows the same result:

```
kubectl get csistoragecapacities -o=json -n topolvm-system
{
    "apiVersion": "v1",
    "items": [],
    "kind": "List",
    "metadata": {
        "resourceVersion": "",
        "selfLink": ""
    }
}
```
@little-guy-lxr : I will appreciate any help  or clue with this. Could it be the we need to add something in the original topolvm project? Thx!

**Comment by little-guy-lxr** [comment]
> I have verified the error in the e2e tests:
> 
> ```
> • Failure [0.068 seconds]
> TopoLVM
> /home/runner/work/topolvm-operator/topolvm-operator/e2e/suite_test.go:137
>   storagecapacity
>   /home/runner/work/topolvm-operator/topolvm-operator/e2e/suite_test.go:141
>     should csistoragecapacities create and update [It]
>     /home/runner/work/topolvm-operator/topolvm-operator/e2e/storagecapacity_test.go:69
> 
>     Expected
>         <int>: 0
>     to equal
>         <int>: 3
> ```
> 
> It seems that it is because the command: `kubectl get csistoragecapacities -o=json -n topolvm-system` does not return any items...
> 
> I do not know what is the cause of this error, because as i understand it depends of the k8 version used, so i do not know why this modification is affecting the e2e test. In the test cluster i have used for manual testing with this changes, everything works , but the output of the same command shows the same result:
> 
> ```
> kubectl get csistoragecapacities -o=json -n topolvm-system
> {
>     "apiVersion": "v1",
>     "items": [],
>     "kind": "List",
>     "metadata": {
>         "resourceVersion": "",
>         "selfLink": ""
>     }
> }
> ```
> 
> @little-guy-lxr : I will appreciate any help or clue with this. Could it be the we need to add something in the original topolvm project? Thx!
could you provide csi external-provisioner version.

**Comment by little-guy-lxr** [comment]
> I have verified the error in the e2e tests:
> 
> ```
> • Failure [0.068 seconds]
> TopoLVM
> /home/runner/work/topolvm-operator/topolvm-operator/e2e/suite_test.go:137
>   storagecapacity
>   /home/runner/work/topolvm-operator/topolvm-operator/e2e/suite_test.go:141
>     should csistoragecapacities create and update [It]
>     /home/runner/work/topolvm-operator/topolvm-operator/e2e/storagecapacity_test.go:69
> 
>     Expected
>         <int>: 0
>     to equal
>         <int>: 3
> ```
> 
> It seems that it is because the command: `kubectl get csistoragecapacities -o=json -n topolvm-system` does not return any items...
> 
> I do not know what is the cause of this error, because as i understand it depends of the k8 version used, so i do not know why this modification is affecting the e2e test. In the test cluster i have used for manual testing with this changes, everything works , but the output of the same command shows the same result:
> 
> ```
> kubectl get csistoragecapacities -o=json -n topolvm-system
> {
>     "apiVersion": "v1",
>     "items": [],
>     "kind": "List",
>     "metadata": {
>         "resourceVersion": "",
>         "selfLink": ""
>     }
> }
> ```
> 
> @little-guy-lxr : I will appreciate any help or clue with this. Could it be the we need to add something in the original topolvm project? Thx!

plase

**Comment by little-guy-lxr** [comment]
@jmolmo  please provide the csi external provisioner container log.

**Comment by jmolmo** [comment]
> @jmolmo could you provide kubernetes version and csi external-provisioner version. beacuse CSIStorageCapacity is off by default if your k8s version is lower then 1.21, so you should turn on it.

This is the version used in my lab, but the same problem happens in the github CI tests 
```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
```

> @jmolmo please provide the csi external provisioner container log.

```
# kubectl  logs topolvm-controller-78467b5c94-xn2rf csi-provisioner -n topolvm-system
W1105 16:54:44.391864       1 feature_gate.go:237] Setting GA feature gate Topology=true. It will be removed in a future release.
I1105 16:54:44.392015       1 csi-provisioner.go:138] Version: 
I1105 16:54:44.392064       1 csi-provisioner.go:161] Building kube configs for running in cluster...
I1105 16:54:44.396403       1 common.go:111] Probing CSI driver for readiness
I1105 16:54:44.400456       1 csi-provisioner.go:277] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
I1105 16:54:45.602566       1 request.go:665] Waited for 1.185517852s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
I1105 16:54:48.810026       1 csi-provisioner.go:416] using apps/v1/Deployment topolvm-controller as owner of CSIStorageCapacity objects
I1105 16:54:48.810652       1 nodes.go:205] Started node topology worker
I1105 16:54:48.812355       1 leaderelection.go:248] attempting to acquire leader lease topolvm-system/topolvm-cybozu-com...
I1105 16:54:48.824781       1 leaderelection.go:258] successfully acquired lease topolvm-system/topolvm-cybozu-com
I1105 16:54:48.926151       1 controller.go:810] Starting provisioner controller topolvm.cybozu.com_topolvm-controller-78467b5c94-xn2rf_ca007dd3-e18e-426d-ac8b-12dbbf8d28e4!
I1105 16:54:48.926259       1 capacity.go:231] Starting Capacity Controller
I1105 16:54:48.926361       1 capacity.go:243] Started Capacity Controller
I1105 16:54:48.926418       1 volume_store.go:97] Starting save volume queue
I1105 16:54:49.027041       1 controller.go:859] Started provisioner controller topolvm.cybozu.com_topolvm-controller-78467b5c94-xn2rf_ca007dd3-e18e-426d-ac8b-12dbbf8d28e4!
```

**Comment by little-guy-lxr** [comment]
> > @jmolmo could you provide kubernetes version and csi external-provisioner version. beacuse CSIStorageCapacity is off by default if your k8s version is lower then 1.21, so you should turn on it.
> 
> This is the version used in my lab, but the same problem happens in the github CI tests
> 
> ```
> # kubectl version
> Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
> ```
> 
> > @jmolmo please provide the csi external provisioner container log.
> 
> ```
> # kubectl  logs topolvm-controller-78467b5c94-xn2rf csi-provisioner -n topolvm-system
> W1105 16:54:44.391864       1 feature_gate.go:237] Setting GA feature gate Topology=true. It will be removed in a future release.
> I1105 16:54:44.392015       1 csi-provisioner.go:138] Version: 
> I1105 16:54:44.392064       1 csi-provisioner.go:161] Building kube configs for running in cluster...
> I1105 16:54:44.396403       1 common.go:111] Probing CSI driver for readiness
> I1105 16:54:44.400456       1 csi-provisioner.go:277] CSI driver does not support PUBLISH_UNPUBLISH_VOLUME, not watching VolumeAttachments
> I1105 16:54:45.602566       1 request.go:665] Waited for 1.185517852s due to client-side throttling, not priority and fairness, request: GET:https://10.96.0.1:443/apis/storage.k8s.io/v1beta1?timeout=32s
> I1105 16:54:48.810026       1 csi-provisioner.go:416] using apps/v1/Deployment topolvm-controller as owner of CSIStorageCapacity objects
> I1105 16:54:48.810652       1 nodes.go:205] Started node topology worker
> I1105 16:54:48.812355       1 leaderelection.go:248] attempting to acquire leader lease topolvm-system/topolvm-cybozu-com...
> I1105 16:54:48.824781       1 leaderelection.go:258] successfully acquired lease topolvm-system/topolvm-cybozu-com
> I1105 16:54:48.926151       1 controller.go:810] Starting provisioner controller topolvm.cybozu.com_topolvm-controller-78467b5c94-xn2rf_ca007dd3-e18e-426d-ac8b-12dbbf8d28e4!
> I1105 16:54:48.926259       1 capacity.go:231] Starting Capacity Controller
> I1105 16:54:48.926361       1 capacity.go:243] Started Capacity Controller
> I1105 16:54:48.926418       1 volume_store.go:97] Starting save volume queue
> I1105 16:54:49.027041       1 controller.go:859] Started provisioner controller topolvm.cybozu.com_topolvm-controller-78467b5c94-xn2rf_ca007dd3-e18e-426d-ac8b-12dbbf8d28e4!
> ```

@jmolmo  please push again force to trigger new pipline.

**Comment by little-guy-lxr** [comment]
@jmolmo  the image (quay.io/topolvm/topolvm-with-sidecar:0.10)  only support k8s version higher than 1.21.  but pipeinline support highest k8s verison is 1.20.     Now I have upgrade pipline k8s versoin. please rebase and push again.

I cherry pick your commit , and e2e passed. see https://github.com/alauda/topolvm-operator/pull/58

**Comment by little-guy-lxr** [comment]
@jmolmo  close this pr,  replace this with #58

**Pull request closed without merging**
